#!/usr/bin/env python3
"""Generates RENN/Resources/Looks/dev_warm.cube: a DEVELOPMENT FIXTURE LUT.

Not an approved RENN Look asset. It exists only so the LUT stage of the render graph
is exercised before the owner's reviewed LUTs arrive (M08). Deterministic output.
"""
from pathlib import Path

N = 17
OUT = Path(__file__).resolve().parent.parent / "RENN/Resources/Looks/dev_warm.cube"


def curve(x: float) -> float:
    """Gentle S-curve with lifted blacks and soft highlights."""
    s = x * x * (3 - 2 * x)
    return 0.04 + (0.7 * x + 0.3 * s) * 0.93


def main() -> None:
    lines = [
        "# DEVELOPMENT FIXTURE - not an approved RENN Look asset.",
        "# Generated by scripts/generate_dev_lut.py. Replaced by the owner's reviewed LUTs in M08.",
        'TITLE "RENN DEV warm (fixture)"',
        f"LUT_3D_SIZE {N}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
    ]
    # .cube order: red varies fastest, then green, then blue.
    for b in range(N):
        for g in range(N):
            for r in range(N):
                red, green, blue = (v / (N - 1) for v in (r, g, b))
                out = (min(1.0, curve(red) * 1.03 + 0.01), curve(green) * 0.99, curve(blue) * 0.86 + 0.03)
                lines.append(" ".join(f"{v:.6f}" for v in out))
    OUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
